"""empty message

Revision ID: 13d191f14724
Revises: 38c8e063fd05
Create Date: 2020-02-19 22:24:38.488375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d191f14724'
down_revision = '38c8e063fd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cohort', 'cohort_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_foreign_key(None, 'student', 'cohort', ['cohort_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.alter_column('cohort', 'cohort_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
