"""empty message

Revision ID: 504e954d4ddb
Revises: 13d191f14724
Create Date: 2020-02-19 22:26:02.969163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504e954d4ddb'
down_revision = '13d191f14724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cohort', 'cohort_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_index(op.f('ix_cohort_cohort_name'), 'cohort', ['cohort_name'], unique=False)
    op.create_foreign_key(None, 'student', 'cohort', ['cohort_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_index(op.f('ix_cohort_cohort_name'), table_name='cohort')
    op.alter_column('cohort', 'cohort_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
