"""empty message

Revision ID: 9bf5b25f498a
Revises: d755621e94ab
Create Date: 2020-02-19 21:58:37.338888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf5b25f498a'
down_revision = 'd755621e94ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_name', sa.String(length=64), nullable=False),
    sa.Column('graduation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('student', sa.Column('cohort_id', sa.Integer(), nullable=True))
    op.alter_column('student', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('student', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_foreign_key(None, 'student', 'cohort', ['cohort_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.alter_column('student', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('student', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('student', 'cohort_id')
    op.drop_table('cohort')
    # ### end Alembic commands ###
