"""empty message

Revision ID: a06c8a8e2575
Revises: 730b5d833a14
Create Date: 2020-02-22 15:24:52.170386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06c8a8e2575'
down_revision = '730b5d833a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'student', 'cohort', ['cohort_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    # ### end Alembic commands ###
