"""empty message

Revision ID: a67fc6b510af
Revises: a5bb519f11be
Create Date: 2020-02-19 22:33:12.552644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67fc6b510af'
down_revision = 'a5bb519f11be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cohort_cohort_name'), 'cohort', ['cohort_name'], unique=False)
    op.create_foreign_key(None, 'student', 'cohort', ['cohort_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_index(op.f('ix_cohort_cohort_name'), table_name='cohort')
    # ### end Alembic commands ###
