"""empty message

Revision ID: d755621e94ab
Revises: eff06fe92d4f
Create Date: 2020-02-19 20:11:00.489057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd755621e94ab'
down_revision = 'eff06fe92d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('student', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('student', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
